[tool.poetry]
name = "arknights-word-count"
version = "2.4.3"
description = "《明日方舟》字词统计"
authors = ["Shawn Sun <lengyanyu258@outlook.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
xlwings = { version = "*", extras = ["all"] }
tqdm = "*"
zhon = "*"

[tool.poetry.group.dev.dependencies]
black = "*"


[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
