name: Download & Extract Fonts
description: "下载字体文件"

defaults:
  run:
    shell: bash

runs:
  using: "composite"
  steps:
    - name: Download Sarasa Gothic Mono Slab SC TTF Release Asset
      id: download_7z
      uses: robinraju/release-downloader@v1.11
      with:
        # The source repository path.
        # Expected format {owner}/{repo}
        # Default: ${{ github.repository }}
        repository: "be5invis/Sarasa-Gothic"

        # A flag to set the download target as latest release
        # The default value is 'false'
        latest: true

        # The name of the file to download.
        # Use this field only to specify filenames other than tarball or zipball, if any.
        # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
        fileName: "SarasaMonoSlabSC-TTF-Unhinted-*.7z"

        # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
        # It will create the target directory automatically if not present
        # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
        out-file-path: "tmp"

    - name: Extract downloaded 7z file Asset
      # p7zip-full is already the newest version (ubuntu-latest).
      run: 7z x -t7z -otmp ${{ fromJson(steps.download_7z.outputs.downloaded_files)[0] }}
