name: Proceed to Update & Commit
description: "下载字体缓存后更新数据，自动提交至仓库后进行部署"

runs:
  using: "composite"
  steps:
    - name: Fetch cache fonts
      uses: actions/cache@v4
      id: cache-fonts
      with:
        path: tmp
        key: SarasaMonoSlabSC-TTF-Unhinted-fonts-cache

    - name: Download Fonts (if not cached)
      if: steps.cache-fonts.outputs.cache-hit != 'true'
      uses: ./.github/actions/download-fonts

    - run: poetry run python main.py --all --auto_update --publish
      shell: bash

    - name: Auto commit to repo.
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # Optional. Commit message for the created commit.
        # Defaults to "Apply automatic changes"
        commit_message: "docs(pages): AUTO update data."

        # Optional. Options used by `git-commit`.
        # See https://git-scm.com/docs/git-commit#_options
        commit_options: "--no-verify --signoff"

        # Optional glob pattern of files which should be added to the commit
        # Defaults to all (.)
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        file_pattern: "docs/"

        # Optional. Option used by `git-status` to determine if the repository is
        # dirty. See https://git-scm.com/docs/git-status#_options
        status_options: "--untracked-files=no"

        # Optional. Options used by `git-add`.
        # See https://git-scm.com/docs/git-add#_options
        add_options: "-u"

        # Optional. Skip internal call to `git fetch`
        skip_fetch: true

        # Optional. Skip internal call to `git checkout`
        skip_checkout: true

        # Optional. Prevents the shell from expanding filenames.
        # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
        disable_globbing: true

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload docs/website/ directory
        path: "docs/website/"

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
