name: Prepare Dependences
description: "准备环境依赖"

runs:
  using: "composite"
  steps:
    - name: Checkout ArknightsGameData Repo.
      uses: actions/checkout@v4
      with:
        repository: "Kengxxiao/ArknightsGameData"
        path: "Github/ArknightsGameData"
        filter: "blob:none"
        sparse-checkout: "zh_CN/gamedata/"

    - name: Checkout ArknightsGameResource Repo.
      uses: actions/checkout@v4
      with:
        repository: "yuanyan3060/ArknightsGameResource"
        path: "Github/ArknightsGameResource"
        filter: "blob:none"
        sparse-checkout: "gamedata/"

    - name: Setup uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        # Whether to restore the cache if found
        restore-cache: "true"

        # Whether to save the cache after the run
        save-cache: "true"

        # Upload managed Python installations to the GitHub Actions cache
        cache-python: "true"

    - run: uv sync --no-group dev
      shell: bash
      env:
        UV_INDEX_URL: https://pypi.org/simple
